<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.PEhuGXg' shared service.

return $this->privates['.service_locator.PEhuGXg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'pageModel' => ['privates', '.errored..service_locator.PEhuGXg.Contao\\PageModel', NULL, 'Cannot autowire service ".service_locator.PEhuGXg": it references class "Contao\\PageModel" but no such service exists.'],
], [
    'pageModel' => 'Contao\\PageModel',
]);
