<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.J8GJ4zW.contao.fragment._contao.frontend_module.two_factor' shared service.

return ($this->privates['.service_locator.J8GJ4zW'] ?? $this->load('get_ServiceLocator_J8GJ4zWService.php'))->withContext('contao.fragment._contao.frontend_module.two_factor', $this);
