<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.o_SvUd3' shared service.

return $this->privates['.service_locator.o_SvUd3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'model' => ['privates', '.errored..service_locator.o_SvUd3.Contao\\ContentModel', NULL, 'Cannot autowire service ".service_locator.o_SvUd3": it references class "Contao\\ContentModel" but no such service exists.'],
], [
    'model' => 'Contao\\ContentModel',
]);
