<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.mt6FK0z' shared service.

return $this->privates['.service_locator.mt6FK0z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'cron' => ['services', 'Contao\\CoreBundle\\Cron\\Cron', 'getCronService.php', true],
], [
    'cron' => 'Contao\\CoreBundle\\Cron\\Cron',
]);
