<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'http-kernel'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ArgumentValueResolverInterface.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'http-kernel'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ArgumentResolver'.\DIRECTORY_SEPARATOR.'ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'Contao\\CoreBundle\\Controller\\ContentElement\\MarkdownController::__invoke' => ['privates', '.service_locator.o_SvUd3', 'get_ServiceLocator_OSvUd3Service.php', true],
    'Contao\\CoreBundle\\Controller\\FrontendController::cronAction' => ['privates', '.service_locator.mt6FK0z', 'get_ServiceLocator_Mt6FK0zService.php', true],
    'Contao\\CoreBundle\\Controller\\FrontendModule\\TwoFactorController::__invoke' => ['privates', '.service_locator.8Gr37N4', 'get_ServiceLocator_8Gr37N4Service.php', true],
    'Contao\\CoreBundle\\Controller\\Page\\RootPageController::__invoke' => ['privates', '.service_locator.PEhuGXg', 'get_ServiceLocator_PEhuGXgService.php', true],
    'Contao\\CoreBundle\\Controller\\ContentElement\\MarkdownController:__invoke' => ['privates', '.service_locator.o_SvUd3', 'get_ServiceLocator_OSvUd3Service.php', true],
    'Contao\\CoreBundle\\Controller\\ContentElement\\MarkdownController' => ['privates', '.service_locator.o_SvUd3', 'get_ServiceLocator_OSvUd3Service.php', true],
    'Contao\\CoreBundle\\Controller\\FrontendController:cronAction' => ['privates', '.service_locator.mt6FK0z', 'get_ServiceLocator_Mt6FK0zService.php', true],
    'Contao\\CoreBundle\\Controller\\FrontendModule\\TwoFactorController:__invoke' => ['privates', '.service_locator.8Gr37N4', 'get_ServiceLocator_8Gr37N4Service.php', true],
    'Contao\\CoreBundle\\Controller\\FrontendModule\\TwoFactorController' => ['privates', '.service_locator.8Gr37N4', 'get_ServiceLocator_8Gr37N4Service.php', true],
    'Contao\\CoreBundle\\Controller\\Page\\RootPageController:__invoke' => ['privates', '.service_locator.PEhuGXg', 'get_ServiceLocator_PEhuGXgService.php', true],
    'Contao\\CoreBundle\\Controller\\Page\\RootPageController' => ['privates', '.service_locator.PEhuGXg', 'get_ServiceLocator_PEhuGXgService.php', true],
], [
    'Contao\\CoreBundle\\Controller\\ContentElement\\MarkdownController::__invoke' => '?',
    'Contao\\CoreBundle\\Controller\\FrontendController::cronAction' => '?',
    'Contao\\CoreBundle\\Controller\\FrontendModule\\TwoFactorController::__invoke' => '?',
    'Contao\\CoreBundle\\Controller\\Page\\RootPageController::__invoke' => '?',
    'Contao\\CoreBundle\\Controller\\ContentElement\\MarkdownController:__invoke' => '?',
    'Contao\\CoreBundle\\Controller\\ContentElement\\MarkdownController' => '?',
    'Contao\\CoreBundle\\Controller\\FrontendController:cronAction' => '?',
    'Contao\\CoreBundle\\Controller\\FrontendModule\\TwoFactorController:__invoke' => '?',
    'Contao\\CoreBundle\\Controller\\FrontendModule\\TwoFactorController' => '?',
    'Contao\\CoreBundle\\Controller\\Page\\RootPageController:__invoke' => '?',
    'Contao\\CoreBundle\\Controller\\Page\\RootPageController' => '?',
]));
