<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.command.resize_images' shared service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'core-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'ResizeImagesCommand.php';

$this->privates['contao.command.resize_images'] = $instance = new \Contao\CoreBundle\Command\ResizeImagesCommand(($this->services['contao.image.image_factory'] ?? $this->load('getContao_Image_ImageFactoryService.php')), ($this->services['contao.image.resizer'] ?? $this->load('getContao_Image_ResizerService.php')), 'C:/laragon/www/entwicklung/vendor/maniaxatwork/contao-portfolio-bundle/assets/images', ($this->privates['contao.image.deferred_image_storage'] ?? $this->load('getContao_Image_DeferredImageStorageService.php')), ($this->services['filesystem'] ?? ($this->services['filesystem'] = new \Symfony\Component\Filesystem\Filesystem())));

$instance->setName('contao:resize-images');

return $instance;
