<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.command.symlinks' shared service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'core-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'SymlinksCommand.php';

$this->services['contao.command.symlinks'] = $instance = new \Contao\CoreBundle\Command\SymlinksCommand(\dirname(__DIR__, 4), 'files', (\dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'logs'), ($this->services['contao.resource_finder'] ?? $this->getContao_ResourceFinderService()), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));

$instance->setName('contao:symlinks');

return $instance;
