<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.image.resizer' shared service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'image'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'ResizerInterface.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'image'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Resizer.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'image'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'DeferredResizerInterface.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'image'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'DeferredResizer.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'core-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Framework'.\DIRECTORY_SEPARATOR.'FrameworkAwareInterface.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'core-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Framework'.\DIRECTORY_SEPARATOR.'FrameworkAwareTrait.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'core-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Image'.\DIRECTORY_SEPARATOR.'LegacyResizer.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'image'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'ResizeCalculator.php';

$this->services['contao.image.resizer'] = $instance = new \Contao\CoreBundle\Image\LegacyResizer('C:/laragon/www/entwicklung/vendor/maniaxatwork/contao-portfolio-bundle/assets/images', ($this->privates['contao.image.resize_calculator'] ?? ($this->privates['contao.image.resize_calculator'] = new \Contao\Image\ResizeCalculator())), ($this->services['filesystem'] ?? ($this->services['filesystem'] = new \Symfony\Component\Filesystem\Filesystem())), ($this->privates['contao.image.deferred_image_storage'] ?? $this->load('getContao_Image_DeferredImageStorageService.php')));

$instance->setFramework(($this->services['contao.framework'] ?? $this->getContao_FrameworkService()));

return $instance;
