<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'cache_warmer' shared service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'http-kernel'.\DIRECTORY_SEPARATOR.'CacheWarmer'.\DIRECTORY_SEPARATOR.'CacheWarmerAggregate.php';

return $this->services['cache_warmer'] = new \Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate(new RewindableGenerator(function () {
    yield 0 => ($this->privates['translation.warmer'] ?? $this->load('getTranslation_WarmerService.php'));
    yield 1 => ($this->privates['router.cache_warmer'] ?? $this->load('getRouter_CacheWarmerService.php'));
    yield 2 => ($this->privates['annotations.cache_warmer'] ?? $this->load('getAnnotations_CacheWarmerService.php'));
    yield 3 => ($this->privates['twig.template_cache_warmer'] ?? $this->load('getTwig_TemplateCacheWarmerService.php'));
    yield 4 => ($this->services['contao.cache.warm_internal'] ?? $this->load('getContao_Cache_WarmInternalService.php'));
    yield 5 => ($this->privates['contao.doctrine.orm.fail_tolerant_proxy_cache_warmer'] ?? $this->load('getContao_Doctrine_Orm_FailTolerantProxyCacheWarmerService.php'));
    yield 6 => ($this->privates['Contao\\CoreBundle\\Twig\\Loader\\ContaoFilesystemLoaderWarmer'] ?? $this->getContaoFilesystemLoaderWarmerService());
}, 7), false, ($this->targetDir.''.'/appContao_ManagerBundle_HttpKernel_ContaoKernelProdContainerDeprecations.log'));
