<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Contao\CoreBundle\EventListener\DataContainer\ContentCompositionListener' shared service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'core-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'DataContainer'.\DIRECTORY_SEPARATOR.'ContentCompositionListener.php';

return $this->services['Contao\\CoreBundle\\EventListener\\DataContainer\\ContentCompositionListener'] = new \Contao\CoreBundle\EventListener\DataContainer\ContentCompositionListener(($this->services['contao.framework'] ?? $this->getContao_FrameworkService()), ($this->services['security.helper'] ?? $this->getSecurity_HelperService()), ($this->privates['Contao\\CoreBundle\\Routing\\Page\\PageRegistry'] ?? $this->getPageRegistryService()), ($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['doctrine.dbal.default_connection'] ?? $this->getDoctrine_Dbal_DefaultConnectionService()), ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
