<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.crawl.escargot_factory' shared service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'core-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Crawl'.\DIRECTORY_SEPARATOR.'Escargot'.\DIRECTORY_SEPARATOR.'Factory.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'terminal42'.\DIRECTORY_SEPARATOR.'escargot'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Subscriber'.\DIRECTORY_SEPARATOR.'SubscriberInterface.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'core-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Crawl'.\DIRECTORY_SEPARATOR.'Escargot'.\DIRECTORY_SEPARATOR.'Subscriber'.\DIRECTORY_SEPARATOR.'EscargotSubscriberInterface.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'terminal42'.\DIRECTORY_SEPARATOR.'escargot'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EscargotAwareInterface.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'terminal42'.\DIRECTORY_SEPARATOR.'escargot'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Subscriber'.\DIRECTORY_SEPARATOR.'ExceptionSubscriberInterface.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'terminal42'.\DIRECTORY_SEPARATOR.'escargot'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EscargotAwareTrait.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'terminal42'.\DIRECTORY_SEPARATOR.'escargot'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'SubscriberLoggerTrait.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'core-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Crawl'.\DIRECTORY_SEPARATOR.'Escargot'.\DIRECTORY_SEPARATOR.'Subscriber'.\DIRECTORY_SEPARATOR.'BrokenLinkCheckerSubscriber.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'core-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Crawl'.\DIRECTORY_SEPARATOR.'Escargot'.\DIRECTORY_SEPARATOR.'Subscriber'.\DIRECTORY_SEPARATOR.'SearchIndexSubscriber.php';

$this->services['contao.crawl.escargot_factory'] = $instance = new \Contao\CoreBundle\Crawl\Escargot\Factory(($this->services['doctrine.dbal.default_connection'] ?? $this->getDoctrine_Dbal_DefaultConnectionService()), ($this->services['contao.framework'] ?? $this->getContao_FrameworkService()), [], []);

$a = ($this->services['translator'] ?? $this->getTranslatorService());

$b = new \Contao\CoreBundle\Crawl\Escargot\Subscriber\BrokenLinkCheckerSubscriber($a);

$c = ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService());

$b->setLogger($c);
$d = new \Contao\CoreBundle\Crawl\Escargot\Subscriber\SearchIndexSubscriber(($this->services['contao.search.indexer'] ?? $this->load('getContao_Search_IndexerService.php')), $a);
$d->setLogger($c);

$instance->addSubscriber($b);
$instance->addSubscriber($d);

return $instance;
