<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.listener.Z6uZ2NA' shared service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'core-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'GlobalsMapListener.php';

return $this->services['contao.listener.Z6uZ2NA'] = new \Contao\CoreBundle\EventListener\GlobalsMapListener(['FE_MOD' => ['user' => ['two_factor' => 'Contao\\ModuleProxy']]]);
