<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.menu.backend_menu_builder' shared service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'core-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Menu'.\DIRECTORY_SEPARATOR.'BackendMenuBuilder.php';

return $this->services['contao.menu.backend_menu_builder'] = new \Contao\CoreBundle\Menu\BackendMenuBuilder(($this->services['knp_menu.factory'] ?? $this->load('getKnpMenu_FactoryService.php')), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));
