<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.install_tool' shared service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'installation-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'InstallTool.php';

return $this->services['contao.install_tool'] = new \Contao\InstallationBundle\InstallTool(($this->services['doctrine.dbal.default_connection'] ?? $this->getDoctrine_Dbal_DefaultConnectionService()), \dirname(__DIR__, 4), ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()), ($this->privates['Contao\\CoreBundle\\Migration\\MigrationCollection'] ?? $this->load('getMigrationCollectionService.php')));
