<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.image.deferred_image_storage' shared service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'image'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'DeferredImageStorageInterface.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'image'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'DeferredImageStorageFilesystem.php';

return $this->privates['contao.image.deferred_image_storage'] = new \Contao\Image\DeferredImageStorageFilesystem('C:/laragon/www/entwicklung/vendor/maniaxatwork/contao-portfolio-bundle/assets/images', ($this->services['filesystem'] ?? ($this->services['filesystem'] = new \Symfony\Component\Filesystem\Filesystem())));
