<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.listener.doctrine_schema' shared service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'core-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'DoctrineSchemaListener.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'core-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Doctrine'.\DIRECTORY_SEPARATOR.'Schema'.\DIRECTORY_SEPARATOR.'DcaSchemaProvider.php';

return $this->privates['contao.listener.doctrine_schema'] = new \Contao\CoreBundle\EventListener\DoctrineSchemaListener(new \Contao\CoreBundle\Doctrine\Schema\DcaSchemaProvider(($this->services['contao.framework'] ?? $this->getContao_FrameworkService()), ($this->services['doctrine'] ?? $this->getDoctrineService()), ($this->privates['Contao\\CoreBundle\\Doctrine\\Schema\\SchemaProvider'] ?? $this->load('getSchemaProviderService.php'))));
