<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.listener.pretty_error_screens' shared service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'core-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'PrettyErrorScreenListener.php';

return $this->privates['contao.listener.pretty_error_screens'] = new \Contao\CoreBundle\EventListener\PrettyErrorScreenListener(true, ($this->services['twig'] ?? $this->getTwigService()), ($this->services['contao.framework'] ?? $this->getContao_FrameworkService()), ($this->services['security.helper'] ?? $this->getSecurity_HelperService()));
