<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.listener.menu.backend_logout' shared service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'core-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'Menu'.\DIRECTORY_SEPARATOR.'BackendLogoutListener.php';

return $this->privates['contao.listener.menu.backend_logout'] = new \Contao\CoreBundle\EventListener\Menu\BackendLogoutListener(($this->services['security.helper'] ?? $this->getSecurity_HelperService()), ($this->services['router'] ?? $this->getRouterService()), ($this->services['security.logout_url_generator'] ?? $this->getSecurity_LogoutUrlGeneratorService()), ($this->services['translator'] ?? $this->getTranslatorService()));
