<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.image.picture_generator' shared service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'image'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'PictureGeneratorInterface.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'image'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'PictureGenerator.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'image'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'ResizeCalculator.php';

return $this->services['contao.image.picture_generator'] = new \Contao\Image\PictureGenerator(($this->services['contao.image.resizer'] ?? $this->load('getContao_Image_ResizerService.php')), ($this->privates['contao.image.resize_calculator'] ?? ($this->privates['contao.image.resize_calculator'] = new \Contao\Image\ResizeCalculator())));
