<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.slug.generator' shared service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'ausi'.\DIRECTORY_SEPARATOR.'slug-generator'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'SlugGeneratorInterface.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'ausi'.\DIRECTORY_SEPARATOR.'slug-generator'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'SlugGenerator.php';

return $this->services['contao.slug.generator'] = new \Ausi\SlugGenerator\SlugGenerator(['validChars' => '0-9a-z']);
