<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.public_alias.Lexik\Bundle\MaintenanceBundle\Command\DriverLockCommand' shared service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'maintenance-bundle-deprecated'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'DriverLockCommand.php';

return $this->services['console.command.public_alias.Lexik\\Bundle\\MaintenanceBundle\\Command\\DriverLockCommand'] = new \Lexik\Bundle\MaintenanceBundle\Command\DriverLockCommand(($this->services['lexik_maintenance.driver.factory'] ?? $this->getLexikMaintenance_Driver_FactoryService()));
