<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Contao\CoreBundle\Command\DebugContaoTwigCommand' shared service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'core-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'DebugContaoTwigCommand.php';

$this->privates['Contao\\CoreBundle\\Command\\DebugContaoTwigCommand'] = $instance = new \Contao\CoreBundle\Command\DebugContaoTwigCommand(($this->privates['Contao\\CoreBundle\\Twig\\Loader\\ContaoFilesystemLoader'] ?? $this->getContaoFilesystemLoaderService()), ($this->privates['Contao\\CoreBundle\\Twig\\Loader\\ContaoFilesystemLoaderWarmer'] ?? $this->getContaoFilesystemLoaderWarmerService()), ($this->privates['Contao\\CoreBundle\\Twig\\Loader\\ThemeNamespace'] ?? ($this->privates['Contao\\CoreBundle\\Twig\\Loader\\ThemeNamespace'] = new \Contao\CoreBundle\Twig\Loader\ThemeNamespace())), \dirname(__DIR__, 4));

$instance->setName('debug:contao-twig');

return $instance;
