<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Contao\CoreBundle\Image\Studio\FigureRenderer' shared service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'core-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Image'.\DIRECTORY_SEPARATOR.'Studio'.\DIRECTORY_SEPARATOR.'FigureRenderer.php';

return $this->services['Contao\\CoreBundle\\Image\\Studio\\FigureRenderer'] = new \Contao\CoreBundle\Image\Studio\FigureRenderer(($this->services['Contao\\CoreBundle\\Image\\Studio\\Studio'] ?? $this->load('getStudioService.php')), ($this->services['twig'] ?? $this->getTwigService()));
