<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Contao\CoreBundle\Controller\InitializeController' shared service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'core-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'InitializeController.php';

return $this->services['Contao\\CoreBundle\\Controller\\InitializeController'] = new \Contao\CoreBundle\Controller\InitializeController(($this->services['contao.framework'] ?? $this->getContao_FrameworkService()), ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), ($this->services['http_kernel'] ?? $this->getHttpKernelService()), ($this->services['kernel'] ?? $this->get('kernel', 1)));
