<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Contao\CoreBundle\Controller\ImagesController' shared service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'core-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ImagesController.php';

return $this->services['Contao\\CoreBundle\\Controller\\ImagesController'] = new \Contao\CoreBundle\Controller\ImagesController(($this->services['contao.image.image_factory'] ?? $this->load('getContao_Image_ImageFactoryService.php')), ($this->services['contao.image.resizer'] ?? $this->load('getContao_Image_ResizerService.php')), 'C:/laragon/www/entwicklung/vendor/maniaxatwork/contao-portfolio-bundle/assets/images', ($this->services['filesystem'] ?? ($this->services['filesystem'] = new \Symfony\Component\Filesystem\Filesystem())));
