<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Contao\CoreBundle\Command\MigrateCommand' shared service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'core-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'MigrateCommand.php';

$this->privates['Contao\\CoreBundle\\Command\\MigrateCommand'] = $instance = new \Contao\CoreBundle\Command\MigrateCommand(($this->privates['Contao\\CoreBundle\\Migration\\MigrationCollection'] ?? $this->load('getMigrationCollectionService.php')), ($this->services['contao.resource_locator'] ?? $this->load('getContao_ResourceLocatorService.php')), \dirname(__DIR__, 4), ($this->services['contao.framework'] ?? $this->getContao_FrameworkService()), ($this->services['contao.installer'] ?? $this->load('getContao_InstallerService.php')));

$instance->setName('contao:migrate');

return $instance;
