<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_security.ua_parser.ua_php.provider' shared service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'ua-parser'.\DIRECTORY_SEPARATOR.'uap-php'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'AbstractParser.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'ua-parser'.\DIRECTORY_SEPARATOR.'uap-php'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'ParserFactoryMethods.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'ua-parser'.\DIRECTORY_SEPARATOR.'uap-php'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Parser.php';

return $this->privates['nelmio_security.ua_parser.ua_php.provider'] = \UAParser\Parser::create();
