<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.PEhuGXg.Contao\PageModel' shared service.

$this->throw('Cannot autowire service ".service_locator.PEhuGXg": it references class "Contao\\PageModel" but no such service exists.');
