<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Contao\CoreBundle\EventListener\DataContainer\PageTypeOptionsListener' shared service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'core-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'DataContainer'.\DIRECTORY_SEPARATOR.'PageTypeOptionsListener.php';

return $this->services['Contao\\CoreBundle\\EventListener\\DataContainer\\PageTypeOptionsListener'] = new \Contao\CoreBundle\EventListener\DataContainer\PageTypeOptionsListener(($this->privates['Contao\\CoreBundle\\Routing\\Page\\PageRegistry'] ?? $this->getPageRegistryService()), ($this->services['security.helper'] ?? $this->getSecurity_HelperService()), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));
