<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Contao\CoreBundle\EventListener\DataContainer\PageUrlListener' shared service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'core-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'DataContainer'.\DIRECTORY_SEPARATOR.'PageUrlListener.php';

return $this->services['Contao\\CoreBundle\\EventListener\\DataContainer\\PageUrlListener'] = new \Contao\CoreBundle\EventListener\DataContainer\PageUrlListener(($this->services['contao.framework'] ?? $this->getContao_FrameworkService()), ($this->services['contao.slug'] ?? $this->load('getContao_SlugService.php')), ($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['doctrine.dbal.default_connection'] ?? $this->getDoctrine_Dbal_DefaultConnectionService()));
