<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Contao\CoreBundle\Controller\RobotsTxtController' shared service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'core-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'RobotsTxtController.php';

return $this->services['Contao\\CoreBundle\\Controller\\RobotsTxtController'] = new \Contao\CoreBundle\Controller\RobotsTxtController(($this->services['contao.framework'] ?? $this->getContao_FrameworkService()), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));
