<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'scheb_two_factor.security.listener.trusted_device' shared service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'scheb'.\DIRECTORY_SEPARATOR.'2fa-trusted-device'.\DIRECTORY_SEPARATOR.'Security'.\DIRECTORY_SEPARATOR.'Http'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'TrustedDeviceListener.php';

return $this->privates['scheb_two_factor.security.listener.trusted_device'] = new \Scheb\TwoFactorBundle\Security\Http\EventListener\TrustedDeviceListener(($this->privates['scheb_two_factor.default_trusted_device_manager'] ?? $this->load('getSchebTwoFactor_DefaultTrustedDeviceManagerService.php')));
