<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Contao\CoreBundle\Image\Studio\Studio' shared service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'core-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Image'.\DIRECTORY_SEPARATOR.'Studio'.\DIRECTORY_SEPARATOR.'Studio.php';

return $this->services['Contao\\CoreBundle\\Image\\Studio\\Studio'] = new \Contao\CoreBundle\Image\Studio\Studio((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'Contao\\CoreBundle\\Image\\Studio\\Studio' => ['services', 'Contao\\CoreBundle\\Image\\Studio\\Studio', 'getStudioService.php', true],
    'contao.assets.files_context' => ['services', 'contao.assets.files_context', 'getContao_Assets_FilesContextService.php', true],
    'contao.framework' => ['services', 'contao.framework', 'getContao_FrameworkService', false],
    'contao.image.image_factory' => ['services', 'contao.image.image_factory', 'getContao_Image_ImageFactoryService.php', true],
    'contao.image.picture_factory' => ['services', 'contao.image.picture_factory', 'getContao_Image_PictureFactoryService.php', true],
    'contao.image.resizer' => ['services', 'contao.image.resizer', 'getContao_Image_ResizerService.php', true],
    'event_dispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
], [
    'Contao\\CoreBundle\\Image\\Studio\\Studio' => 'Contao\\CoreBundle\\Image\\Studio\\Studio',
    'contao.assets.files_context' => 'Contao\\CoreBundle\\Asset\\ContaoContext',
    'contao.framework' => '?',
    'contao.image.image_factory' => '?',
    'contao.image.picture_factory' => '?',
    'contao.image.resizer' => 'Contao\\Image\\ResizerInterface',
    'event_dispatcher' => 'event_dispatcher',
]))->withContext('Contao\\CoreBundle\\Image\\Studio\\Studio', $this), \dirname(__DIR__, 4), 'files', $this->parameters['contao.image.valid_extensions']);
