<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container05RrlLW\appContao_ManagerBundle_HttpKernel_ContaoKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container05RrlLW/appContao_ManagerBundle_HttpKernel_ContaoKernelProdContainer.php') {
    touch(__DIR__.'/Container05RrlLW.legacy');

    return;
}

if (!\class_exists(appContao_ManagerBundle_HttpKernel_ContaoKernelProdContainer::class, false)) {
    \class_alias(\Container05RrlLW\appContao_ManagerBundle_HttpKernel_ContaoKernelProdContainer::class, appContao_ManagerBundle_HttpKernel_ContaoKernelProdContainer::class, false);
}

return new \Container05RrlLW\appContao_ManagerBundle_HttpKernel_ContaoKernelProdContainer([
    'container.build_hash' => '05RrlLW',
    'container.build_id' => 'efc981fa',
    'container.build_time' => 1666010710,
], __DIR__.\DIRECTORY_SEPARATOR.'Container05RrlLW');
