services:
    Maniax\ContaoHoliday\EventListener\Contao\DCA\TlManiaxContaoHolidayItem:
        public: true
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
            - '@contao.slug'
            - '@request_stack'
            - '@twig'

    Maniax\ContaoHoliday\EventListener\Contao\DCA\TlManiaxContaoHolidayDoc:
        public: true
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
            - '@contao.slug'
            - '@request_stack'
            - '@twig'

    # Contao Hooks
    Maniax\ContaoHoliday\EventListener\Contao\BackendMenuListener:
        public: true
        tags:
            - { name: kernel.event_listener, event: contao.backend_menu_build, priority: -255 }
        arguments:
          - '@router'
          - '@request_stack'

    Maniax\ContaoHoliday\EventListener\Contao\DCA\TlModule:
        public: true
        arguments: ['@Doctrine\Persistence\ManagerRegistry']

    Maniax\ContaoHoliday\EventListener\Contao\Hooks\CompileFormFieldsListener:
        public: true
        arguments: ['@request_stack']
