Maniax\ContaoHoliday\Controller\Contao\BackendModule\SettingsController:
    path: /contao/maniaxcontaoholiday/settings
    defaults:
        _scope: backend
        _controller: Maniax\ContaoHoliday\Controller\Contao\BackendModule\SettingsController::showSettings
