services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Maniax\ContaoHoliday\:
        resource: ../../../src
        exclude: ../../../src/{Entity,Migrations,Resources,Tests}

    inspiredminds.fieldsetduplication.helper.field:
        class: InspiredMinds\ContaoFieldsetDuplication\Helper\FieldHelper
