services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Maniax\ContaoHoliday\:
        resource: ../../../src
        exclude: ../../../src/{Entity,Migrations,Resources,Tests}

    InspiredMinds\ContaoFieldsetDuplication\Helper\FieldHelper: '@inspiredminds.fieldsetduplication.helper.field'
